chimera:
  directory:
    input: directoryIn
    output: directoryOut
  amqp:
    exchange: messagingChimera.topic
    queue: messagingChimera.files
    routingKey: messageChimera.incomingFile
  document:
    extensions:
      - ".txt"
      - ".pdf"

spring:
  rabbitmq:
    username: guest
    password: guest
    requested-heartbeat: 60
